--TALLER PRÁCTICA

--PUNTO 1
SELECT CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
GROUP BY CITY
HAVING COUNT(EMPLOYEE_ID) BETWEEN 5 AND 15;

--PUNTO 2
SELECT INITCAP(LAST_NAME)||', '||UPPER(FIRST_NAME) NOMBRE_COMPLETO,
       TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) MESES,
       TO_CHAR(SALARY+SALARY*NVL(COMMISSION_PCT,0),'$999999999.99') SALARIO,
       TO_CHAR(HIRE_DATE, 'Day, DD/Month/YY') FECHA_CONTRATO,
       DECODE(SALARY, 20000, 'ELITE', 15000, 'GOLD', 10000, 'PREMIUM', 'SILVER') CATE
FROM EMPLOYEES;

--PUNTO 3
SELECT COUNTRY_NAME
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, JOBS J
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND E.JOB_ID=J.JOB_ID
AND UPPER(JOB_TITLE) IN ('SALES MANAGER', 'PROGRAMMER')
AND MOD(EXTRACT(MONTH FROM HIRE_DATE),2)=0
AND EXTRACT(YEAR FROM HIRE_DATE)>=EXTRACT(YEAR FROM SYSDATE)-5
GROUP BY COUNTRY_NAME
HAVING COUNT(EMPLOYEE_ID)>=5;

--PUNTO 4
SELECT EXTRACT(YEAR FROM HIRE_DATE) ANIO
FROM EMPLOYEES
WHERE MOD(EXTRACT(YEAR FROM HIRE_DATE),2)<>0
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
HAVING COUNT(EMPLOYEE_ID)>7;

--PUNTO 5
SELECT DISTINCT M.FIRST_NAME||' '||M.LAST_NAME
FROM EMPLOYEES M, EMPLOYEES E
WHERE MOD(SUBSTR(REPLACE(M.PHONE_NUMBER,'.'),1,1)+SUBSTR(REPLACE(M.PHONE_NUMBER,'.'),4,1),2)=0
AND M.EMPLOYEE_ID=E.MANAGER_ID;

--PUNTO 6
SELECT FIRST_NAME||' '||LAST_NAME NOMBRE,
       TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) MESES,
       EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE)+18 EDAD
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND D.LOCATION_ID=L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND C.REGION_ID=R.REGION_ID
AND UPPER(REGION_NAME) LIKE UPPER('&NOMBRE');

